DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE(
	id number(20) PRIMARY KEY,
	realName varchar(100),
	name varchar(100),
	email VARCHAR(100),
	cellphone varchar(100),
	department varchar(100),
	homePath varchar(100),
	workPath varchar(100),
	idCardNo VARCHAR(100),
	healthInsuranceCardType VARCHAR(100),
	healthInsuranceCardNo VARCHAR(100),
	role_id NUMBER(20)
);
DROP TABLE LOGININFO;
CREATE TABLE LOGININFO(
	id NUMBER(20) PRIMARY KEY,
	name varchar(100),
	password varchar(100),
	state NUMBER(10),
	rememberdays NUMBER(10)
);
DROP TABLE ROLE_MENU;
DROP TABLE ROLE;
DROP SEQUENCE ROLE_SEQ;
CREATE SEQUENCE ROLE_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
CREATE TABLE ROLE(
	id NUMBER(20) PRIMARY KEY,
	name varchar(100),
	describe VARCHAR(100)
);
DROP SEQUENCE MENU_SEQ;
CREATE SEQUENCE MENU_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE MENU;
CREATE TABLE MENU(
	id NUMBER(20) PRIMARY KEY,
	parent_id NUMBER(20),
	NAME VARCHAR(100),
	URL VARCHAR(100),
	ORDERID NUMBER(5),
	TYPE NUMBER(2),
	ICONNAME VARCHAR(100)
);
CREATE TABLE ROLE_MENU(
	role_id NUMBER(20),
	menu_id NUMBER(20)
);
ALTER TABLE ROLE_MENU
ADD CONSTRAINT FK_ROLE_MENU_ROLE
FOREIGN KEY(role_id) REFERENCES ROLE(id);
ALTER TABLE ROLE_MENU
ADD CONSTRAINT FK_ROLE_MENU_MENU
FOREIGN KEY(menu_id) REFERENCES MENU(id);

DROP SEQUENCE SYSLOGINFO_SEQ;
CREATE SEQUENCE SYSLOGINFO_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE SYSLOGINFO;
CREATE TABLE SYSLOGINFO(
	id NUMBER(20),
	type NUMBER(2),
	content VARCHAR(100),
	lastLoginTime Date,
	lastExitTime Date,
	currentLoginTime Date,
	currentExitTime Date,
	ip VARCHAR(100)
);


COMMIT;


