DROP TABLE TASKITEM;
DROP TABLE TASK;
DROP TABLE ORDERITEM;
DROP TABLE DEPARTMENT_EMPLOYEE;
DROP TABLE HOSPITAL_EMPLOYEE;
DROP TABLE DOCTOR_EMPLOYEE;
DROP TABLE EMPLOYEE;

DROP TABLE DICTIONARY;


DROP TABLE SCHEDULE;
DROP TABLE DOCTOR;
DROP TABLE DEPARTMENT;
DROP TABLE HOSPITAL;
DROP TABLE CITY;
DROP TABLE PROVINCE;
DROP TABLE REGION;
CREATE TABLE EMPLOYEE(
	id number(20) PRIMARY KEY,
	realName varchar(100),
	name varchar(100),
	email VARCHAR(100),
	cellphone varchar(100),
	department varchar(100),
	homePath varchar(100),
	workPath varchar(100),
	idCardNo VARCHAR(100),
	healthInsuranceCardType VARCHAR(100),
	healthInsuranceCardNo VARCHAR(100),
	role_id NUMBER(20)
);
DROP TABLE LOGININFO;
CREATE TABLE LOGININFO(
	id NUMBER(20) PRIMARY KEY,
	name varchar(100),
	password varchar(100),
	state NUMBER(10),
	rememberdays NUMBER(10)
);
DROP TABLE ROLE_MENU;
DROP TABLE ROLE;
DROP SEQUENCE ROLE_SEQ;
CREATE SEQUENCE ROLE_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
CREATE TABLE ROLE(
	id NUMBER(20) PRIMARY KEY,
	name varchar(100),
	describe VARCHAR(100)
);
DROP SEQUENCE MENU_SEQ;
CREATE SEQUENCE MENU_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE MENU;
CREATE TABLE MENU(
	id NUMBER(20) PRIMARY KEY,
	parent_id NUMBER(20),
	NAME VARCHAR(100),
	URL VARCHAR(100),
	ORDERID NUMBER(5),
	TYPE NUMBER(2),
	ICONNAME VARCHAR(100)
);
CREATE TABLE ROLE_MENU(
	role_id NUMBER(20),
	menu_id NUMBER(20)
);
ALTER TABLE ROLE_MENU
ADD CONSTRAINT FK_ROLE_MENU_ROLE
FOREIGN KEY(role_id) REFERENCES ROLE(id);
ALTER TABLE ROLE_MENU
ADD CONSTRAINT FK_ROLE_MENU_MENU
FOREIGN KEY(menu_id) REFERENCES MENU(id);

DROP SEQUENCE SYSLOGINFO_SEQ;
CREATE SEQUENCE SYSLOGINFO_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE SYSLOGINFO;
CREATE TABLE SYSLOGINFO(
	id NUMBER(20),
	type NUMBER(2),
	content VARCHAR(100),
	lastLoginTime Date,
	lastExitTime Date,
	currentLoginTime Date,
	currentExitTime Date,
	ip VARCHAR(100)
);
DROP SEQUENCE APPLICATION_SEQ;
CREATE SEQUENCE APPLICATION_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE APPLICATION;
CREATE TABLE APPLICATION(
	id NUMBER(20),
	name VARCHAR(100),
	brief VARCHAR(100),
	starttime Date,
	endtime Date,
	state NUMBER(2),
	docpath VARCHAR(100)
);
DROP SEQUENCE FEEDBACK_SEQ;
CREATE SEQUENCE FEEDBACK_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE FEEDBACK;
CREATE TABLE FEEDBACK(
	id NUMBER(20),
	content VARCHAR(100)
);

DROP SEQUENCE TASK_SEQ;
CREATE SEQUENCE TASK_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
CREATE TABLE TASK(
	id NUMBER(20) PRIMARY KEY,
	name VARCHAR(100),
	month NUMBER(2),
	taskcycle NUMBER(2),
	describe VARCHAR(100),
	type NUMBER(2),
	state NUMBER(2),
	starttime Date,
	endtime Date,
	employee_id NUMBER(20)
);
ALTER TABLE TASK
ADD CONSTRAINT FK_EMPLOYEE_TASK
FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id);

DROP SEQUENCE TASKITEM_SEQ;
CREATE SEQUENCE TASKITEM_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
CREATE TABLE TASKITEM(
	id NUMBER(20),
	itemCycle NUMBER(2),
	itemtype NUMBER(2),
	itemdescribe varchar(100),
	department varchar(100),
	state NUMBER(2),
	task_id NUMBER(20),
	employee_id NUMBER(20)
);
ALTER TABLE TASKITEM
ADD CONSTRAINT FK_EMPLOYEE_TASKITEM
FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id);

ALTER TABLE TASKITEM
ADD CONSTRAINT FK_TASK_TASKITEM
FOREIGN KEY(task_id) REFERENCES TASK(id);

COMMIT;


