DROP SEQUENCE REGION_SEQ;
CREATE SEQUENCE REGION_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE REGION;
CREATE TABLE REGION(
	id number(20) PRIMARY KEY,
	name VARCHAR(100)
);


DROP SEQUENCE PROVINCE_SEQ;
CREATE SEQUENCE PROVINCE_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE PROVINCE;
CREATE TABLE PROVINCE(
	id number(20) PRIMARY KEY,
	name VARCHAR(100),
	region_id number(20)
);
ALTER TABLE PROVINCE
ADD CONSTRAINT FK_REGION_PROVINCE
FOREIGN KEY(region_id) REFERENCES REGION(id);


DROP SEQUENCE CITY_SEQ;
CREATE SEQUENCE CITY_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE CITY;
CREATE TABLE CITY(
	id number(20) PRIMARY KEY,
	name VARCHAR(100),
	pinyin VARCHAR(100),
	zip VARCHAR(100),
	level VARCHAR(100),
	province_id number(20)
);
ALTER TABLE CITY
ADD CONSTRAINT FK_PROVINCE_CITY
FOREIGN KEY(province_id) REFERENCES PROVINCE(id);

DROP SEQUENCE HOSPITAL_SEQ;
CREATE SEQUENCE HOSPITAL_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE HOSPITAL;
CREATE TABLE HOSPITAL(
	id number(20) PRIMARY KEY,
	name VARCHAR(100),
	pic VARCHAR(100),
	ghTotal NUMBER(20),
	ghHighScore NUMBER(20),
	domain VARCHAR(100),
	logo VARCHAR(100),
	address VARCHAR(100),
	x NUMBER(10,5),
	Y NUMBER(10,5),
	tel VARCHAR(100),
	fax VARCHAR(100),
	zipcode VARCHAR(100),
	url VARCHAR(100),
	mail VARCHAR(100),
	gobus VARCHAR(5000),
	level VARCHAR(100),
	nature VARCHAR(100),
	mtype VARCHAR(100),
	comment NUMBER(20),
	count   NUMBER(20),
	type   VARCHAR(100),
	city_id number(20)
);

ALTER TABLE HOSPITAL
ADD CONSTRAINT FK_CITY_HOSPITAL
FOREIGN KEY(city_id) REFERENCES CITY(id);





DROP SEQUENCE DEPARTMENT_SEQ;
CREATE SEQUENCE DEPARTMENT_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE DEPARTMENT;
CREATE TABLE DEPARTMENT(
	id number(20) PRIMARY KEY,
	code VARCHAR(100),
	pinyin VARCHAR(100),
	type VARCHAR(100),
	level VARCHAR(100),
	pic VARCHAR(100),
	phone VARCHAR(100),
	name  VARCHAR(100),
	message VARCHAR(3000),
	ghTotal NUMBER(20),
	ghHighScore NUMBER(20),
	hospital_id number(20)
);
ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_HOSPITAL_DEPARTMENT
FOREIGN KEY(hospital_id) REFERENCES DEPARTMENT(id);


DROP SEQUENCE DOCTOR_SEQ;
CREATE SEQUENCE DOCTOR_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE DOCTOR;
CREATE TABLE DOCTOR(
	id number(20) PRIMARY KEY,
	name VARCHAR(100),
	pic VARCHAR(100),
	introduce VARCHAR(100),
	ghTotal NUMBER(20),
	ghHighScore NUMBER(20),
	department_id number(20),
	hospital_id  NUMBER(20)
);
ALTER TABLE DOCTOR
ADD CONSTRAINT FK_DEPARTMENT_DOCTOR
FOREIGN KEY(department_id) REFERENCES DEPARTMENT(id);

ALTER TABLE DOCTOR
ADD CONSTRAINT FK_HOSPITAL_DOCTOR
FOREIGN KEY(hospital_id) REFERENCES HOSPITAL(id);


DROP SEQUENCE SCHEDULE_SEQ;
CREATE SEQUENCE SCHEDULE_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE SCHEDULE;
CREATE TABLE SCHEDULE(
	id number(20) PRIMARY KEY,
	date Date,
	numbers NUMBER(20),
	cost NUMBER(20,2),
	residueNumbers NUMBER(5),
	noonType NUMBER(2),
	doctor_id number(20)
);
ALTER TABLE SCHEDULE
ADD CONSTRAINT FK_DOCTOR_SCHEDULE
FOREIGN KEY(doctor_id) REFERENCES DOCTOR(id);


DROP SEQUENCE ORDERITEM_SEQ;
CREATE SEQUENCE ORDERITEM_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE ORDERITEM;
CREATE TABLE ORDERITEM(
	id number(20) PRIMARY KEY,
	date Date,
	orderNum NUMBER(20),
	state NUMBER(20),
	takepassword VARCHAR(100),
	score NUMBER(20),
	message VARCHAR(100),
	hospital_id number(20),
	department_id number(20),
	doctor_id number(20),
	employee_id number(20)
);

ALTER TABLE ORDERITEM
ADD CONSTRAINT FK_HOSPITAL_ORDERITEM
FOREIGN KEY(hospital_id) REFERENCES HOSPITAL(id);
ALTER TABLE ORDERITEM
ADD CONSTRAINT FK_DEPARTMENT_ORDERITEM
FOREIGN KEY(department_id) REFERENCES DEPARTMENT(id);
ALTER TABLE ORDERITEM
ADD CONSTRAINT FK_DOCTOR_ORDERITEM
FOREIGN KEY(doctor_id) REFERENCES DOCTOR(id);
ALTER TABLE ORDERITEM
ADD CONSTRAINT FK_EMPLOYEE_ORDERITEM
FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id);


DROP SEQUENCE DICTIONARY_SEQ;
CREATE SEQUENCE DICTIONARY_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	CACHE 10;
DROP TABLE DICTIONARY;
CREATE TABLE DICTIONARY(
	id number(20) PRIMARY KEY,
	name VARCHAR(100),
	type VARCHAR(100)
);



CREATE TABLE DEPARTMENT_EMPLOYEE(
	department_id NUMBER(20),
	employee_id NUMBER(20),
	type NUMBER(2) 
);
ALTER TABLE DEPARTMENT_EMPLOYEE
ADD CONSTRAINT FK_DEPARTMENT_DEPARTMENT_EMPLOYEE
FOREIGN KEY(department_id) REFERENCES DEPARTMENT(id);

ALTER TABLE DEPARTMENT_EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT_EMPLOYEE
FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id);


CREATE TABLE HOSPITAL_EMPLOYEE(
	hospital_id NUMBER(20),
	employee_id NUMBER(20),
	type NUMBER(2) 
);
ALTER TABLE HOSPITAL_EMPLOYEE
ADD CONSTRAINT FK_HOSPITAL_HOSPITAL_EMPLOYEE
FOREIGN KEY(hospital_id) REFERENCES HOSPITAL(id);

ALTER TABLE HOSPITAL_EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_HOSPITAL_EMPLOYEE
FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id);


CREATE TABLE DOCTOR_EMPLOYEE(
	doctor_id NUMBER(20),
	employee_id NUMBER(20),
	type NUMBER(2) 
);
ALTER TABLE DOCTOR_EMPLOYEE
ADD CONSTRAINT FK_DOCTOR_DOCTOR_EMPLOYEE
FOREIGN KEY(doctor_id) REFERENCES DOCTOR(id);

ALTER TABLE DOCTOR_EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_DOCTOR_EMPLOYEE
FOREIGN KEY(employee_id) REFERENCES EMPLOYEE(id);



commit;













